const nouns = [
  "Cat", "Dog", "Fox", "Wolf", "Bear",
  "Lion", "Tiger", "Panda", "Koala", "Otter",
  "Eagle", "Hawk", "Falcon", "Owl", "Raven",
  "Crow", "Penguin", "Dolphin", "Whale", "Shark",
  "Turtle", "Rabbit", "Bunny", "Deer", "Moose",
  "Horse", "Pony", "Zebra", "Giraffe", "Monkey",
  "Gorilla", "Cheetah", "Leopard", "Jaguar", "Panther",
  "Cobra", "Python", "Gecko", "Lizard", "Dragon",
  "Phoenix", "Unicorn", "Robot", "Alien", "Ninja",
  "Pirate", "Wizard", "Knight", "Ghost", "Zombie",
  "Viking", "Samurai", "Ranger", "Hunter", "Pilot",
  "Racer", "Gamer", "Hacker", "Coder", "Maker",
  "Runner", "Skater", "Surfer", "Rider", "Explorer",
  "Voyager", "Nomad", "Captain", "King", "Queen",
  "Prince", "Hero", "Legend", "Master", "Boss",
  "Chief", "Ace", "Champ", "Star", "Comet",
  "Meteor", "Orbit", "Rocket", "Galaxy", "Planet",
  "Moon", "Sun", "Cloud", "Storm", "Fire",
  "Flame", "Spark", "Bolt", "Shadow", "Pixel",
  "Byte", "Glitch", "Cookie",

  "Badger", "Beaver", "Bison", "Buffalo", "Camel",
  "Canary", "Chameleon", "Chipmunk", "Coyote", "Crane",
  "Donkey", "Duck", "Elk", "Ferret", "Flamingo",
  "Gazelle", "Goat", "Goose", "Hamster", "Hedgehog",
  "Hippo", "Hyena", "Iguana", "Jackal", "Kangaroo",
  "Lemur", "Llama", "Lobster", "Mammoth", "Mantis",
  "Meerkat", "Mole", "Otter", "Ostrich", "Parrot",
  "Peacock", "Pelican", "Pigeon", "Rabbit", "Ram",
  "Seal", "Sloth", "Snail", "Sparrow", "Spider",
  "Squid", "Swan", "Tapir", "Toad", "Toucan",
  "Walrus", "Wasp", "Weasel", "Yak", "Viper",

  "Arrow", "Axe", "Blade", "Bow", "Cannon",
  "Dagger", "Hammer", "Lance", "Shield", "Sword",
  "Spear", "Whip", "Rocket", "Laser", "Cannon",
  "Engine", "Motor", "Wheel", "Gear", "Spring",
  "Chain", "Bolt", "Nail", "Key", "Lock",
  "Ring", "Crown", "Mask", "Cape", "Boot",
  "Glove", "Helmet", "Armor", "Badge", "Coin",
  "Token", "Medal", "Trophy", "Banner", "Flag",
  "Map", "Compass", "Lantern", "Torch", "Beacon",
  "Anchor", "Rope", "Sail", "Ship", "Boat",

  "Apple", "Mango", "Peach", "Pear", "Plum",
  "Berry", "Cherry", "Lemon", "Lime", "Melon",
  "Orange", "Coconut", "Banana", "Papaya", "Kiwi",
  "Guava", "Olive", "Peanut", "Cookie", "Biscuit",
  "Donut", "Muffin", "Waffle", "Pancake", "Pretzel",
  "Noodle", "Taco", "Pizza", "Burger", "Popcorn",
  "Candy", "Jelly", "Toffee", "Caramel", "Cocoa",
  "Mocha", "Latte", "Coffee", "Tea", "Soda",

  "River", "Lake", "Ocean", "Island", "Mountain",
  "Valley", "Forest", "Jungle", "Desert", "Canyon",
  "Cave", "Cliff", "Hill", "Meadow", "Garden",
  "Beach", "Coast", "Wave", "Tide", "Reef",
  "Coral", "Rock", "Stone", "Pebble", "Crystal",
  "Diamond", "Ruby", "Emerald", "Sapphire", "Quartz",
  "Cloud", "Rain", "Snow", "Wind", "Breeze",
  "Thunder", "Lightning", "Rainbow", "Sunset", "Sunrise",

  "Star", "Moon", "Comet", "Meteor", "Asteroid",
  "Galaxy", "Planet", "Saturn", "Mars", "Venus",
  "Jupiter", "Neptune", "Cosmos", "Nebula", "Nova",
  "Orbit", "Eclipse", "Rocket", "Satellite", "Spaceship",
  "Alien", "Astronaut", "Asteroid", "Meteorite", "Galaxy",

  "Apple", "Pixel", "Byte", "Bit", "Code",
  "Bug", "Glitch", "Bot", "App", "Link",
  "Cloud", "Server", "Node", "Stack", "Script",
  "Query", "Cache", "Data", "Chip", "Drive",
  "Screen", "Cursor", "Mouse", "Keyboard", "Console",
  "Game", "Quest", "Level", "Score", "Boss",
  "Player", "Avatar", "Portal", "Dungeon", "Castle",
  "Tower", "Temple", "Arena", "World", "Realm",

  "Drum", "Guitar", "Piano", "Violin", "Trumpet",
  "Flute", "Bass", "Beat", "Song", "Tune",
  "Melody", "Rhythm", "Note", "Chord", "Voice",
  "Dance", "Groove", "Disco", "Stage", "Radio",

  "Book", "Page", "Story", "Novel", "Poem",
  "Pen", "Pencil", "Brush", "Canvas", "Frame",
  "Photo", "Camera", "Film", "Movie", "Scene",
  "Dream", "Idea", "Thought", "Memory", "Secret",

  "Street", "Road", "Bridge", "Tunnel", "Train",
  "Bus", "Taxi", "Bike", "Cycle", "Car",
  "Truck", "Jeep", "Van", "Plane", "Jet",
  "Helicopter", "Ship", "Ferry", "Cruise", "Train",

  "Wizard", "Mage", "Knight", "Warrior", "Archer",
  "Rogue", "Paladin", "Ranger", "Monk", "Druid",
  "Dragon", "Goblin", "Troll", "Giant", "Elf",
  "Orc", "Dwarf", "Demon", "Spirit", "Ghost",
  "Vampire", "Werewolf", "Monster", "Beast", "Titan",

  "Hammer", "Rocket", "Blaster", "Cyborg", "Android",
  "Machine", "Gadget", "Widget", "Device", "Drone",
  "Robot", "Mecha", "Circuit", "Battery", "Magnet",
  "Plasma", "Photon", "Laser", "Fusion", "Reactor",

  "Fox", "Panda", "Tiger", "Wolf", "Bear",
  "Lion", "Eagle", "Raven", "Hawk", "Owl",
  "Cobra", "Viper", "Python", "Dragon", "Phoenix",
  "Falcon", "Jaguar", "Panther", "Cheetah", "Leopard",

  "Hero", "Villain", "King", "Queen", "Prince",
  "Princess", "Duke", "Baron", "Chief", "Captain",
  "General", "Commander", "Leader", "Boss", "Legend",
  "Champion", "Master", "Guardian", "Keeper", "Ruler",

  "Sailor", "Traveler", "Drifter", "Wanderer", "Walker",
  "Climber", "Diver", "Skier", "Surfer", "Rider",
  "Runner", "Jumper", "Flyer", "Driver", "Pilot",
  "Racer", "Explorer", "Adventurer", "Voyager", "Nomad",

  "Bubble", "Balloon", "Marble", "Dice", "Puzzle",
  "Cube", "Sphere", "Block", "Toy", "Doll",
  "Kite", "YoYo", "Top", "Spinner", "Wheel",
  "Button", "Switch", "Lever", "Spring", "Magnet",

  "Coffee", "Cookie", "Donut", "Muffin", "Waffle",
  "Noodle", "Taco", "Pizza", "Burger", "Bacon",
  "Toast", "Bread", "Cheese", "Honey", "Sugar",
  "Pepper", "Salt", "Spice", "Mint", "Cocoa",

  "Cactus", "Flower", "Rose", "Tulip", "Lily",
  "Daisy", "Oak", "Pine", "Maple", "Willow",
  "Palm", "Bamboo", "Moss", "Fern", "Leaf",
  "Root", "Branch", "Seed", "Vine", "Berry",

  "Castle", "Fort", "Palace", "Tower", "Temple",
  "Shrine", "Village", "City", "Kingdom", "Empire",
  "Realm", "World", "Planet", "Station", "Base",
  "Camp", "Lab", "Factory", "Workshop", "Garage",

  "Whisper", "Echo", "Dream", "Mystery", "Secret",
  "Shadow", "Silence", "Thunder", "Chaos", "Magic",
  "Wonder", "Spirit", "Soul", "Fate", "Destiny",
  "Vision", "Hope", "Lucky", "Fortune", "Chance",
];
module.exports = nouns;
